plugins {
    id 'java'
}

group = 'com.beast'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:0.15.3"
}

// Ye hissa asli magic hai, ye files ko dhoond kar jar mein dalega
jar {
    from sourceSets.main.output
    includeEmptyDirs = false
    manifest {
        attributes('Main-Class': 'com.beast.BeastA1Core')
    }
}
