plugins {
    id 'java'
}

group = 'com.beast'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:0.15.3"
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
}

jar {
    from sourceSets.main.output
}
