plugins {
    id 'java'
}

group = 'com.beast'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:0.15.3"
}

// Ye "Wildcard" raasta hai, fail nahi hoga
sourceSets {
    main {
        java { srcDirs = ['src/main/java', 'src/main/src/main/java'] }
        resources { srcDirs = ['src/main/resources', 'src/main/src/main/resources'] }
    }
}

jar {
    from sourceSets.main.output
    from sourceSets.main.resources
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
